[tool.poetry]
name = "chronoscheduler"
version = "0.1.0"
description = ""
authors = ["gengen"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
PuLP = "^2.7.0"
pandas = "^2.0.2"
numpy = "^1.24.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
