version: '3'
services:
  chronoscheduler-front:
    build:
      context: ../
      dockerfile: environments/Dockerfile
    volumes:
      - .dockerenv:/chronoscheduler/.venv
      - ../:/chronoscheduler
    ports:
      - 8000:8000  # Host:Docker
      - 8888:8888
    environment:
      - WATCHFILES_FORCE_POLLING=true  # ホットリロードするため
    cpuset: '0-23'  # 使用するCPUコアの範囲を指定
    cpus: 24
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '24'